<script setup lang="ts">
import { ref } from 'vue';
import type { ServerInfo } from '../types';

const props = defineProps<{
  info: ServerInfo;
  qrSvg: string | null;
  busy: boolean;
}>();
defineEmits<{ stop: [] }>();

const copied = ref(false);

async function copyUrl() {
  if (!props.info.url) return;
  try {
    await navigator.clipboard.writeText(props.info.url);
    copied.value = true;
    setTimeout(() => (copied.value = false), 1500);
  } catch {
    // Clipboard can be denied; the URL is selectable text anyway.
  }
}
</script>

<template>
  <section v-if="info.running" class="share">
    <h2>Anyone on your Wi-Fi can download</h2>
    <p class="url-row">
      <code class="url">{{ info.url }}</code>
      <button class="copy" @click="copyUrl">{{ copied ? 'Copied!' : 'Copy' }}</button>
    </p>
    <!-- Safe: this SVG is generated by our own Rust code from a URL we
         built. v-html with user-supplied content would be an XSS hole. -->
    <div class="qr" v-html="qrSvg"></div>
    <button class="stop" :disabled="busy" @click="$emit('stop')">Stop Sharing</button>
  </section>
  <p v-else class="stopped">Not sharing. Drop files to start.</p>
</template>
