[package]
name = "mosquito-core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [
  "fs",
  "macros",
  "net",
  "rt-multi-thread",
] }
tokio-util = { "version" = "0.7.19", features = ["io"] }

[dev-dependencies]
http-body-util = "0.1.5"
tempfile = "3.27.0"
tower = { version = "0.5.3", features = ["util"] }
